@url = http://localhost:8080
###

POST {{url}}/api/location HTTP/1.1
Content-Type: application/json

{
  "address": "7 N 8th St",
  "city": "Richmond",
  "state": "VA",
  "zipCode": 23219,
  "addressType": "Home"
}

###

PUT {{url}}/api/location/2 HTTP/1.1
Content-Type: application/json

{
  "locationId": 2,
  "address": "Test Address 2 New",
  "city": "Test City 2",
  "state": "VA",
  "zipCode": 22152,
  "addressType": "Business"
}

###

GET {{url}}/api/location/2 HTTP/1.1

###

DELETE {{url}}/api/location/5 HTTP/1.1

###

GET {{url}}/api/event/business/1 HTTP/1.1

###

GET {{url}}/api/event/2 HTTP/1.1

###

POST {{url}}/api/event HTTP/1.1
Content-Type: application/json

{
  "name": "Test Event Name 3",
  "description": "Test Event Description 3",
  "timeDate": "2024-01-01T05:01:00.000+00:00",
  "businessId": 1
}

###

PUT {{url}}/api/event/2 HTTP/1.1
Content-Type: application/json

{
  "eventId": 2,
  "name": "Test Event Name 2 New",
  "description": "Test Event Description 2",
  "timeDate": "2024-01-01T05:01:00.000+00:00",
  "businessId": 1
}

###

DELETE {{url}}/api/event/3 HTTP/1.1

###

GET {{url}}/api/person/1 HTTP/1.1

###

POST {{url}}/create_account HTTP/1.1
Content-Type: application/json

{
  "username": "newadmin@admin.com",
  "password": "P@ssword1!"
}

###

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "jerry215",
  "password": "020715gP@"
}

###


POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
  "username": "newadmin@admin.com",
  "password": "P@ssword1!"
}

//   "jwt_token": "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJmYWtlLXllbHAtYXBwIiwic3ViIjoibmV3YWRtaW5AYWRtaW4uY29tIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJhcHBVc2VySWQiOjMsImV4cCI6MTY2NDM4OTYxMX0.ih9Bn3IBTg-KNhBZnSr3gLdaKW_MXU5e_vJ3FYt-lhc"


###

GET {{url}}/api/location/business/2 HTTP/1.1


###

GET {{url}}/api/event/business/1 HTTP/1.1

###

GET {{url}}/api/person HTTP/1.1

###

POST {{url}}/api/person HTTP/1.1
Content-Type: application/json

{  "firstName": "Test First Na",
  "middleName": "Test Middle Na",
  "lastName": "Test Last Na",
  "suffix": "S",
  "photoDir": "C:\\Users\\Owner\\Pictures\\logo.png",
  "photoName": "kitty.png",
  "phone": "Test Phone",
  "locations": [],
  "locationId": 1,
  "userId": 1
  }

###

GET {{url}}/api/person/1 HTTP/1.1

###

GET {{url}}/api/business/2 HTTP/1.1

###

POST {{url}}/api/business HTTP/1.1
Content-Type: application/json

{
"name": "The Bannered Mare",
"description": "Tavern in Whiterun",
"photoDir": "C:\\Users\\MFarooqui\\Pictures\\Saved Pictures\\Discord Reacts\\kittyconfuse.png",
"rating": 4.5,
"locationId": 1,
"personId": 3
}

###

PUT {{url}}/api/business/1 HTTP/1.1
Content-Type: application/json

{
"businessId": 1,
"name": "Silver-Blood Inn",
"description": "Tavern in Markarth",
"photoDir": "C:\\Users\\MFarooqui\\Pictures\\Saved Pictures\\Discord Reacts\\kittyconfuse.png",
"rating": 4.5,
"locationId": 3,
"personId": 3
}

###

PUT {{url}}/api/business/2 HTTP/1.1
Content-Type: application/json

{
"businessId": 2,
"name": "The Bee and Barb",
"description": "Tavern in Riften",
"photoDir": "C:\\Users\\MFarooqui\\Pictures\\Saved Pictures\\Discord Reacts\\kittyconfuse.png",
"rating": 4.5,
"locationId": 1,
"personId": 3
}

###

DELETE {{url}}/api/person/1

###
GET {{url}}/api/person/search/t HTTP/1.1

###
GET {{url}}/api/business/search/te HTTP/1.1
